### ISSUE TITLE
plasma 5 -> 6, partial dark variant support

### ISSUE THREAD

**Issue by noraj** [KaOSx/midna#24] opened 2024-03-08 10:45 UTC
It may just be me, but here the behavior I noticed.

On midna theme 6.1.1 (plasma 5 / qt5) when I applied MidnaDark color, it was applying on all windows but also on panels. Now on midna 7.0.2 (plasma 6 / qt 6), it applies to windows but my panels stay in light mode.

I don't remember how it was before, but now I'm only offered a light version for global theme, plasma style. However I have a midna dark variant for window decoration and colors. Also I'm wondering why there is midna kvantum application style but not in plasma settings so I have to choose it in kvantum and apply kvantum application style in plasma settings.

**Comment by demmm** [comment] 2024-03-08 10:51
Midna-dark was never KaOS maintained, but only added since there were community members maintaining it.
That is no longer the case, and nothing was done to port Midna-dark to plasm 6 , thus now broken and no longer part of the midna-themes package:
https://github.com/KaOSx/midna/commit/10eda6404e1285bf6e1b531f29488f5c3b64a112

Kvantum no longer accessible in systemsettings needs investigation, might be Kvantum (upstream) needs changes to be plasma 6 ready.

**Comment by demmm** [comment] 2024-03-08 11:04
Kvantum is an upstream bug:
https://github.com/tsujan/Kvantum/commit/acc46e083b65f65623e7be5ede29f2d0921aea5a

**Comment by demmm** [comment] 2024-03-08 11:39
Wait, this is regarding Plasma 5?
>Also I'm wondering why there is midna kvantum application style but not in plasma settings so I have to choose it in kvantum and apply kvantum application style in plasma settings.

KaOS has no Plasma 5, only Plasma 6, so is this a KaOS report/question?  If so, make sure to be fully updated first.

**Comment by noraj** [comment] 2024-03-08 16:27
The change of behavior appeared on Plasma 6 (midna 7.0.2) https://kaosx.us/packages/view.php?name=apps/midna-themes-7.0.2-1, source https://github.com/KaOSx/apps/blob/7e7f104ad086f1a2d54e40a721847d903e23e400/midna-themes/PKGBUILD#L3-L4.

But on Plasma 5 (midna 6.1.1), source https://github.com/KaOSx/apps/blob/361a9da37eb80f618d8275fa40affefe324f15d4/midna-themes/PKGBUILD#L3-L4 there was no issue on panels.

The Qt6 change appeared not so long ago (2 months): https://github.com/KaOSx/apps/commit/a7efa2c1b7026f587972b6990d2680726cc3fb97. I haven't use the theme so much in the meanwhile. That's why I talk about qt4, because it's think it's the move to qt6 that broke this behavior.

**Comment by noraj** [comment] 2024-03-08 16:29
But as you said this commit https://github.com/KaOSx/midna/commit/10eda6404e1285bf6e1b531f29488f5c3b64a112 from last week dropped support for the dark variant.

**Comment by demmm** [comment] 2024-03-08 16:30
Again, is this about a KaOS install?  There is no Plasma 5, and certainly no Qt4. That is really years and years ago.

**Comment by demmm** [comment] 2024-03-08 16:55
Closing now, since on KaOS there is no issue with Kvantum & systemsettings.  How other distributions package Kvantum has no place in this tracker.
Dropping of midna-dark support is not a bug, but as explained, planned & needed.

**Closed as completed by demmm** 2024-03-08 16:55 UTC

**Comment by noraj** [comment] 2024-03-08 17:13
> Dropping of midna-dark support is not a bug, but as explained, planned & needed.

I understand, that's indeed the answer.

**Comment by demmm** [comment] 2024-03-08 17:15
And to be clear, midna-themes 7 is NOT compatible with plasma 5.

**Comment by noraj** [comment] 2024-03-08 17:18
Yes of course midna 7 is plasma 6 only. I'm on plasma 6. This issue was just about me not finding the dark theme anymore because I didn't know it was dropped. Nothing more.

**Comment by evenbecker** [comment] 2024-04-14 15:46
I have installed KaOS 2024.03. I suggest to also remove midna-dark theme in the plasma colors section. [Distrotube](https://www.youtube.com/watch?v=eLZM0ktmfio) has recently tested KaOS and mentioned that the white buttons are unreadable. People are not aware that the midna-dark theme is not official and may think KaOS is not properly maintained (like Solus), which is not true :)

**Comment by demmm** [comment] 2024-04-14 15:51
> I have installed KaOS 2024.03. I suggest to also remove midna-dark theme in the plasma colors section. [Distrotube](https://www.youtube.com/watch?v=eLZM0ktmfio) has recently tested KaOS and mentioned that the white buttons are unreadable. People are not aware that the midna-dark theme is not official and may think KaOS is not properly maintained (like Solus), which is not true :)

Will do, most was removed already anyway, but if the colors are also broken, then it is time to completely remove from packaging.
